export const CATEGORY_KEYWORDS = {
    MODULAR: [
        "/InfKitGun/",
        "/Barrel/",
        "/OperatorAmplifiers/",
        "/Tip/",
        "/DrifterPistol",
    ],
    ARCH_WEAPONS: [
        "/Archwing/Primary",
        "/Archwing/Melee",
        "/HeavyWeapons/",
        "/ExaltedArtilleryWeapon",
    ],
    VEHICLES: ["/Powersuits/Archwing/", "/Vehicles/", "Voidrig", "Bonewidow"],
    WARFRAMES: ["/Powersuits/"],
    COMPANIONS: ["/Sentinels/", "/Pets/", "/CatbrowPet/", "/KubrowPet/"],
    SECONDARY: [
        "/Pistols/",
        "/Secondary/",
        "/Secondaries/",
        "Pistol",
        "Akimbo",
        "Kunai",
        "/Grimoire/",
        "/ThrowingWeapons/",
        "Detron",
        "MK1Furis",
        "EntratiWristGun",
        "TwinGrakatas",
    ],
    MELEE: [
        "/Melee/",
        "/Blade/",
        "Sword",
        "/LasGooSickle",
        "EntSphereHammer",
        "MK1Bo",
        "MK1Furax",
        "Skana",
        "ElectroProd",
        "EntFistIncarnon",
        "SentJointedScytheWeapon",
    ],
};
