export const RESOURCES = [
    "Credits",
    "Neural Sensors",
    "Neurodes",
    "Orokin Cell",
    "Nano Spores",
    "Plastids",
    "Polymer Bundle",
    "Circuits",
    "Alloy Plate",
    "Ferrite",
    "Salvage",
    "Rubedo",
    "Hexenon",
    "Argon Crystal",
    "Tellurium",
    "Control Module",
    "Morphics",
    "Cryotic",
    "Oxium",
    "Detonite Ampule",
    "Fieldron Sample",
    "Mutagen Sample",
    "Nitain Extract",
    "Kuva",
    "Forma",
    "Detonite Injector",
    "Mutagen Mass",
    "Fieldron",
    "Thrax Plasm",
    "Entrati Lanthorn",
    "Fate Pearl",
    "Gallium",
    "Fish Oil",
    "Radian Sentirum",
    "Seram Beetle Shell",
    "Dull Button",
    "Ganglion",
    "Purged Dagonic",
    "Scintillant",
    "Tubercular Gill System",
    "Aggristone",
    "Kovnik",
    "Rune Marrow",
    "Silphesla",
    "Cabochon Embolos",
    "Trapezium Xenorhast",
    "Techrot Motherboard",
    "Techrot Chitin",
    "Efervon Sample",
    "Höllvanian Pitchweave Fragment",
    "Maw Fang",
    "Saggen Pearl",
    "Yao Shrub",
    "Fish Scales",
    "Nistlepod",
    "Pyrotic Alloy",
    "Tear Azurite",
    "Mirewinder Parallel Biode",
    "Scrap",
    "Venerdo Alloy",
    "Carbides",
    "Isos",
    "Nullstones",
    "Heart Noctrul",
    "Tepa Nodule",
    "Tromyzon Entroplasma",
    "Titanium",
    "Axidrol Alloy",
    "Echowinder Anoscopic Sensor",
    "Thermal Sludge",
    "Smooth Phasmin",
    "Gyromag Systems",
    "Longwinder Lathe Coagulant",
    "Radiant Zodian",
    "Vega Toroid",
    "Ocular Stem-Root",
    "Stellated Necrathene",
    "Mytocardia Spore",
    "Scrubber Exa Brain",
    "Travocyte Alloy",
    "Sola Toroid",
    "Repeller Systems",
    "Marquise Thyst",
    "Cetus Wisp",
    "Murkray Liver",
    "Breath Of The Eidolon",
    "Fersteel Alloy",
    "Marquise Veridos",
    "Maprico",
    "Atmo Systems",
    "Calda Toroid",
    "Charamote Sagan Module",
    "Hespazym Alloy",
    "Connla Sprout",
    "Nacreous Pebble",
    "Tasoma Extract",
    "Entrati Obols",
    "Necracoil",
    "Shrill Voca",
    "Condroc Wing",
    "Mortus Horn",
    "Tralok Eyes",
    "Coprite Alloy",
    "Goopolla Spleen",
    "Aroxium Alloy",
    "Charc Electroplax",
    "Auroxium Alloy",
    "Voidgel Orb",
    "Voidplume Pinion",
    "Voidplume Quill",
    "Goblite Tears",
    "Kriller Thermal Laser",
    "Eye-Eye Rotoblade",
    "Cuthol Tendrils",
    "Star Crimzian",
    "Echo Voca",
    "Recaster Neural Relay",
    "Khut-Khut Venom Sac",
    "Yogwun Stomach",
    "Javlok Capacitor",
    "Norg Brain",
    "Iradite",
    "Esher Devar",
    "Mawfish Bones",
    "Narmer Isoplast",
    "Star Amarast",
    "Grokdrul",
    "Crisma Toroid",
    "Synathid Ecosynth Analyzer",
    "Sapcaddy Venedo Case",
    "Faceted Tiametrite",
    "Ferment Bladder",
    "Pustulite",
    "Adramal Alloy",
    "Benign Infested Tumor",
    "Dendrite Blastoma",
    "Eidolon Shard",
    "Orokin Ducats",
    "Lua Thrax Plasm",
    "Heart Nyth",
    "Intact Sentient Core",
    "Devolved Namalon",
    "Parasitic Tethermaw",
    "Spinal Core Section",
    "Seriglass Shard",
    "Gorgaricus Spore",
    "Pathos Clamp",
    "Kuaka Spinal Claw",
    "Silphsela",
    "Brickie Muon Battery",
    "Sporulate Sac",
    "Lamentus",
    "Dracroot",
    "Eevani",
    "Temporal Dust",
    "Tink Dissipator Coil",
    "Tempered Bapholite",
    "Anomaly Shard",
    "Exceptional Sentient Core",
    "Purified Heciphron",
    "Cranial Foremount",
];
