pub const RESOURCES: &[&str] = &[
    "Adramal Alloy",
    "Aggristone",
    "Alloy Plate",
    "Anomaly Shard",
    "Argon Crystal",
    "Aroxium Alloy",
    "Atmo Systems",
    "Auroxium Alloy",
    "Axidrol Alloy",
    "Benign Infested Tumor",
    "Breath Of The Eidolon",
    "Brickie Muon Battery",
    "Cabochon Embolos",
    "Calda Toroid",
    "Carbides",
    "Cetus Wisp",
    "Charamote Sagan Module",
    "Charc Electroplax",
    "Circuits",
    "Condroc Wing",
    "Connla Sprout",
    "Control Module",
    "Coprite Alloy",
    "Cranial Foremount",
    "Credits",
    "Crisma Toroid",
    "Cryotic",
    "Cuthol Tendrils",
    "Dendrite Blastoma",
    "Detonite Ampule",
    "Detonite Injector",
    "Devolved Namalon",
    "Dracroot",
    "Dull Button",
    "Echo Voca",
    "Echowinder Anoscopic Sensor",
    "Eevani",
    "Efervon Sample",
    "Eidolon Shard",
    "Entrati Lanthorn",
    "Entrati Obols",
    "Esher Devar",
    "Exceptional Sentient Core",
    "Eye-Eye Rotoblade",
    "Faceted Tiametrite",
    "Fate Pearl",
    "Ferment Bladder",
    "Ferrite",
    "Fersteel Alloy",
    "Fieldron Sample",
    "Fieldron",
    "Fish Oil",
    "Fish Scales",
    "Forma",
    "Gallium",
    "Ganglion",
    "Goblite Tears",
    "Goopolla Spleen",
    "Gorgaricus Spore",
    "Grokdrul",
    "Gyromag Systems",
    "Heart Noctrul",
    "Heart Nyth",
    "Hespazym Alloy",
    "Hexenon",
    "Höllvanian Pitchweave Fragment",
    "Intact Sentient Core",
    "Iradite",
    "Isos",
    "Javlok Capacitor",
    "Khut-Khut Venom Sac",
    "Kovnik",
    "Kriller Thermal Laser",
    "Kuaka Spinal Claw",
    "Kuva",
    "Lamentus",
    "Longwinder Lathe Coagulant",
    "Lua Thrax Plasm",
    "Maprico",
    "Marquise Thyst",
    "Marquise Veridos",
    "Maw Fang",
    "Mawfish Bones",
    "Mirewinder Parallel Biode",
    "Morphics",
    "Mortus Horn",
    "Murkray Liver",
    "Mutagen Mass",
    "Mutagen Sample",
    "Mytocardia Spore",
    "Nacreous Pebble",
    "Nano Spores",
    "Narmer Isoplast",
    "Necracoil",
    "Neural Sensors",
    "Neurodes",
    "Nistlepod",
    "Nitain Extract",
    "Norg Brain",
    "Nullstones",
    "Ocular Stem-Root",
    "Orokin Cell",
    "Orokin Ducats",
    "Oxium",
    "Parasitic Tethermaw",
    "Pathos Clamp",
    "Plastids",
    "Polymer Bundle",
    "Purged Dagonic",
    "Purified Heciphron",
    "Pustulite",
    "Pyrotic Alloy",
    "Radian Sentirum",
    "Radiant Zodian",
    "Recaster Neural Relay",
    "Repeller Systems",
    "Rubedo",
    "Rune Marrow",
    "Saggen Pearl",
    "Salvage",
    "Sapcaddy Venedo Case",
    "Scintillant",
    "Scrap",
    "Scrubber Exa Brain",
    "Seram Beetle Shell",
    "Seriglass Shard",
    "Shrill Voca",
    "Silphesla",
    "Silphsela",
    "Smooth Phasmin",
    "Sola Toroid",
    "Spinal Core Section",
    "Sporulate Sac",
    "Star Amarast",
    "Star Crimzian",
    "Stellated Necrathene",
    "Synathid Ecosynth Analyzer",
    "Tasoma Extract",
    "Tear Azurite",
    "Techrot Chitin",
    "Techrot Motherboard",
    "Tellurium",
    "Tempered Bapholite",
    "Temporal Dust",
    "Tepa Nodule",
    "Thermal Sludge",
    "Thrax Plasm",
    "Tink Dissipator Coil",
    "Titanium",
    "Tralok Eyes",
    "Trapezium Xenorhast",
    "Travocyte Alloy",
    "Tromyzon Entroplasma",
    "Tubercular Gill System",
    "Vega Toroid",
    "Venerdo Alloy",
    "Voidgel Orb",
    "Voidplume Pinion",
    "Voidplume Quill",
    "Yao Shrub",
    "Yogwun Stomach",
];
